esp:
  image: gcr.io/endpoints-release/endpoints-runtime:1
  ports:
    - "8082:8082"
    - "8083:8083"
  volumes:
    - "./key:/esp"
  command: >
    -s echo-api.endpoints.sample-202800.cloud.goog
    -v 2018-05-07r2
    -k /esp/serviceaccount.json
    -a "grpc://docker.for.mac.localhost:50051"
    --http_port 8082
    --http2_port 8083
    --cors_preset basic
    --cors_allow_headers *
nginx:
  image: nginx:1.13.12-alpine
  ports:
    - "80:80"
  volumes:
    - ./client/web/default.conf:/etc/nginx/conf.d/default.conf
    - ./client/web/html:/var/www/html
grpcserver:
  image: golang:1.10.2-alpine3.7
  ports:
    - "50051:50051"
  volumes:
    - ".:/go/src/github.com/morix1500/cloudendpoint"
  working_dir: /go/src/github.com/morix1500/cloudendpoint
  command: go run server/main.go
