// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/echo.proto

/*
Package echo is a generated protocol buffer package.

It is generated from these files:
	proto/echo.proto

It has these top-level messages:
	Msg
	Request
	Response
*/
package echo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Msg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Request struct {
	Message *Msg `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetMessage() *Msg {
	if m != nil {
		return m.Message
	}
	return nil
}

type Response struct {
	Message *Msg `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMessage() *Msg {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "echo.Msg")
	proto.RegisterType((*Request)(nil), "echo.Request")
	proto.RegisterType((*Response)(nil), "echo.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EchoService service

type EchoServiceClient interface {
	Echo1(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Echo2(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Echo3(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Echo4(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type echoServiceClient struct {
	cc *grpc.ClientConn
}

func NewEchoServiceClient(cc *grpc.ClientConn) EchoServiceClient {
	return &echoServiceClient{cc}
}

func (c *echoServiceClient) Echo1(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/echo.EchoService/Echo1", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Echo2(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/echo.EchoService/Echo2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Echo3(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/echo.EchoService/Echo3", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoServiceClient) Echo4(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/echo.EchoService/Echo4", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EchoService service

type EchoServiceServer interface {
	Echo1(context.Context, *Request) (*Response, error)
	Echo2(context.Context, *Request) (*Response, error)
	Echo3(context.Context, *Request) (*Response, error)
	Echo4(context.Context, *Request) (*Response, error)
}

func RegisterEchoServiceServer(s *grpc.Server, srv EchoServiceServer) {
	s.RegisterService(&_EchoService_serviceDesc, srv)
}

func _EchoService_Echo1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo1(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Echo2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo2(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Echo3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo3(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoService_Echo4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServiceServer).Echo4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.EchoService/Echo4",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServiceServer).Echo4(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _EchoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*EchoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo1",
			Handler:    _EchoService_Echo1_Handler,
		},
		{
			MethodName: "Echo2",
			Handler:    _EchoService_Echo2_Handler,
		},
		{
			MethodName: "Echo3",
			Handler:    _EchoService_Echo3_Handler,
		},
		{
			MethodName: "Echo4",
			Handler:    _EchoService_Echo4_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/echo.proto",
}

func init() { proto.RegisterFile("proto/echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4d, 0xce, 0xc8, 0xd7, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x29, 0x99, 0xf4,
	0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4, 0xbc, 0xbc, 0xfc, 0x92, 0xc4,
	0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x1a, 0x25, 0x79, 0x2e, 0x66, 0xdf, 0xe2, 0x74, 0x21, 0x09,
	0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x18, 0x57, 0x49, 0x8f, 0x8b, 0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x19, 0x55,
	0x11, 0xb7, 0x11, 0xa7, 0x1e, 0xd8, 0x36, 0xdf, 0xe2, 0x74, 0x84, 0x7a, 0x7d, 0x2e, 0x8e, 0xa0,
	0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa2, 0x34, 0x18, 0x2d, 0x64, 0xe2, 0xe2, 0x76, 0x4d,
	0xce, 0xc8, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x72, 0xe6, 0x62, 0x05, 0x71, 0x0d,
	0x85, 0x78, 0x21, 0x8a, 0xa1, 0xb6, 0x4b, 0xf1, 0xc1, 0xb8, 0x10, 0xc3, 0x95, 0xa4, 0x9b, 0x2e,
	0x3f, 0x99, 0xcc, 0x24, 0xaa, 0xc4, 0xa5, 0x5f, 0x66, 0x08, 0xf6, 0xb5, 0xbe, 0xa1, 0x15, 0xcc,
	0x50, 0x98, 0x21, 0x46, 0xa4, 0x1b, 0x62, 0x84, 0x61, 0x88, 0x31, 0xe9, 0x86, 0x18, 0x63, 0x18,
	0x62, 0x42, 0xba, 0x21, 0x26, 0x70, 0x43, 0x92, 0xd8, 0xc0, 0x91, 0x65, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0xff, 0x5b, 0xe2, 0xe4, 0x01, 0x00, 0x00,
}
